import pygame

KEYBOARD_MAPPING = {
    pygame.K_z: 'C3',
    pygame.K_s: 'C#3',
    pygame.K_x: 'D3',
    pygame.K_d: 'D#3',
    pygame.K_c: 'E3',
    pygame.K_v: 'F3',
    pygame.K_g: 'F#3',
    pygame.K_b: 'G3',
    pygame.K_h: 'G#3',
    pygame.K_n: 'A3',
    pygame.K_j: 'A#3',
    pygame.K_m: 'B3',
    pygame.K_q: 'C4',
    pygame.K_2: 'C#4',
    pygame.K_w: 'D4',
    pygame.K_3: 'D#4',
    pygame.K_e: 'E4',
    pygame.K_r: 'F4',
    pygame.K_5: 'F#4',
    pygame.K_t: 'G4',
    pygame.K_6: 'G#4',
    pygame.K_y: 'A4',
    pygame.K_7: 'A#4',
    pygame.K_u: 'B4',
    pygame.K_i: 'C5',
    pygame.K_9: 'C#5',
    pygame.K_o: 'D5',
    pygame.K_0: 'D#5',
    pygame.K_p: 'E5',
    pygame.K_LEFTBRACKET: 'F5',
    pygame.K_EQUALS: 'F#5',
    pygame.K_RIGHTBRACKET: 'G5',
    pygame.K_BACKSPACE: 'G#5',
    pygame.K_BACKSLASH: 'A5',
}
